### ISSUE TITLE
org.glassfish.jaxb:jaxb-runtime is used but marked as unused

### ISSUE THREAD

**Issue by StefanHirche** [Splitties/refreshVersions#699] opened 2023-08-22 15:21 UTC
- [ ] I have read the [guidelines for submitting issues](https://splitties.github.io/refreshVersions/contributing/submitting-issues/#bug-reports)
## 🐛 Describe the bug
I just changed to 0.60.0, and now the runtimeOnly dependecy to jaxb-runtime is marked as unused, although it is used in 3 projects.
The strange thing is, if i remove the line from version.properties, it is added again with the refreshVersions task, but marked as unused

## ⚠️ Current behavior
The dependecy is marked as unused

## ✅ Expected behavior
It is not marked as unused.

## 💣 Steps to reproduce
Don't know, maybe using jaxb-runtime is enough.

## 📱 Tech info
 - [Build Scan URL](https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg):

**Comment by LouisCAD** [comment] 2023-08-23 23:31
Is this a duplicate of your own #700 issue?

**Comment by LouisCAD** [comment] 2023-08-23 23:52
Do you have the following into your project's `gradle.properties` file or machine's `~/.gradle/gradle.properties` file?
```
org.gradle.configureondemand=true
```

Which Gradle version are you using? 
Also, do you believe it is related to your other issue, #700

**Comment by StefanHirche** [comment] 2023-08-24 10:25
> 1. Do you have the following into your project's `gradle.properties` file or machine's `~/.gradle/gradle.properties` file?
> 
> 
> ```
> org.gradle.configureondemand=true
> ```
No, I don't. But I can check if this changes anything.
>     2. Which Gradle version are you using?
7.6.2
>     3. Can you link a reproducing project?
I will try
>     4. Also, do you believe it is related to your other issue, [Dependencies in the classpath configuration in the buildscript block of build.gradle are marked unused #700](https://github.com/Splitties/refreshVersions/issues/700)
I'm not sure, as I found several similar issues in refreshVersion's issues list, but all only mentioning a destinct artifact dependency, so I just added my problem artifact, as all others are working fine. And this problem occurs in a normal dependency block.

**Comment by LouisCAD** [comment] 2023-08-29 01:34
Can you try with version `0.60.2-SNAPSHOT` and let me know if the issue is fixed?

You'll need to add the snapshots repo. Instructions here:
https://splitties.github.io/refreshVersions/setup/#if-you-want-to-use-a-snapshot-version

I plan to release 0.60.2 this Tuesday, after a good night of sleep.

**Comment by StefanHirche** [comment] 2023-08-29 14:52
I just tested the snapshot and it looks good. No "unused" entries anymore, at least no unexpected ones.
Thanks.

**Comment by LouisCAD** [comment] 2023-08-29 14:53
Great, releasing in several minutes.

**Closed** 2023-08-30 06:31 UTC
