### ISSUE TITLE
Comparison method violates its general contract!

### ISSUE THREAD

**Issue by ravenfeld** [Splitties/refreshVersions#714] opened 2024-02-06 20:51 UTC
- [x] I have read the [guidelines for submitting issues](https://splitties.github.io/refreshVersions/contributing/submitting-issues/#bug-reports)
## 🐛 Describe the bug
I'm in version "0.60.5" and I have a problem when I run the command `./gradlew refreshVersions`
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':refreshVersions'.
> Comparison method violates its general contract!
```

## ⚠️ Current behavior
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':refreshVersions'.
> Comparison method violates its general contract!
```

## ✅ Expected behavior
I don't know if it's a problem with agp 8.2.2 or something else.

## 💣 Steps to reproduce
Launching an Android project in agp 8.2.2 the command `./gradlew refreshVersions`

**Comment by LouisCAD** [comment] 2024-02-07 14:37
Are you certain it happens on a brand new Android project?

Also, duplicate of #645, if you can pinpoint which dependency is causing the issue, please add the info in there (#645).

**Closed by LouisCAD** 2024-02-07 14:37 UTC
