### ISSUE TITLE
Dependencies in the classpath configuration in the buildscript block of build.gradle are marked unused

### ISSUE THREAD

**Issue by StefanHirche** [Splitties/refreshVersions#700] opened 2023-08-22 15:24 UTC
- [ ] I have read the [guidelines for submitting issues](https://splitties.github.io/refreshVersions/contributing/submitting-issues/#bug-reports)
## 🐛 Describe the bug
I just changed to 0.60.0, and now the dependency in the buildscript block to a classpath configuration is marked as unused.
The strange thing is, if i remove the line from version.properties, it is added again with the refreshVersions task, but marked as unused, also different version choices are added, as there are snapshot versions available.

## ⚠️ Current behavior
The dependecy is marked as unused

## ✅ Expected behavior
It is not marked as unused.

## 💣 Steps to reproduce
Don't know, maybe using classpath dependencies in a buildscript block are enough.
## 📱 Tech info
 - [Build Scan URL](https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg):

**Comment by StefanHirche** [comment] 2023-08-23 16:50
I changed the version in my report.

OK, this is my build.gradle in the root project
```
buildscript {
    repositories {
        maven {
            url "http://local.nexus.com/erpo"
            allowInsecureProtocol true
        }
    }
    configurations.classpath {
		resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
		resolutionStrategy.cacheDynamicVersionsFor 0, 'seconds'
	}
    dependencies {
        classpath "group:scripts:_"
    }
}

apply plugin: 'rootProject'
```

Currently there are two versions of script available, 1.0 and 1.1-SNAPSHOT.
Everything is fine with 0.51.0, but with 0.60.0, I get (after deleting the line in the versions.properties) something like
```
#unused
version.group..script=1.0
###                  =1.1-SNAPSHOT
```
(I wrote this by hand, might look sloghtly different)

**Comment by LouisCAD** [comment] 2023-08-23 19:35
Which Gradle version are you on?

**Comment by StefanHirche** [comment] 2023-08-24 10:22
I use gradle 7.6.2

**Comment by brewin** [comment] 2023-08-24 17:42
Here's a [reproducer](https://github.com/brewin/RefreshVersionsBug).

This also reproduces #624 if you comment out the buildscript in the root build.gradle.kts.

**Comment by attila-fazekas** [comment] 2023-08-27 07:14
Same issue here, bunch of my dependencies marked as `unused` ([example here](https://github.com/attila-fazekas/kolibrium/pull/37/files)) even though they are used in `buildSrc` ([see here](https://github.com/attila-fazekas/kolibrium/tree/main/buildSrc))

**Closed** 2023-08-29 01:27 UTC

**Comment by LouisCAD** [comment] 2023-08-29 01:30
I found the culprit and fixed it. Will release 0.60.2 this Tuesday.
You can already try the 0.60.2-SNAPSHOT version.

**Comment by LouisCAD** [comment] 2023-08-29 01:31
Thank you for the simple reproducing projects!
They were helpful to see a project config reproducing the issue, I knew what to put in my test projects.

**Comment by attila-fazekas** [comment] 2023-09-03 18:05
Hi @LouisCAD,

Apparently version 0.60.2 still producing `unused` comments, please see in https://github.com/attila-fazekas/kolibrium/pull/40/files

**Comment by LouisCAD** [comment] 2023-09-04 09:43
This is for dependencies declared in the buildSrc only I can see.

Can you try specifying the version of refreshVersions in the buildSrc too, as documented in the setup guide on the website?

**Comment by attila-fazekas** [comment] 2023-09-04 20:52
Have tried, but got the following error:
```
Error resolving plugin [id: 'de.fayard.refreshVersions', version: '0.60.2']
> The request for this plugin could not be satisfied because the plugin is already on the classpath with an unknown version, so compatibility cannot be checked.
```

**Comment by LouisCAD** [comment] 2023-09-06 13:32
Please, look at the documentation again, there's a part specific to buildSrc.

**Comment by LouisCAD** [comment] 2023-09-27 14:10
Gradle is so unpredictable!

I found another case of dependencies marked as unused, caused by the fact that dependencies are not always there when you expect it. I have no clue why it works fine on a given project, but not on another. Anyway, I will publish another version today or tomorrow.

**Comment by LouisCAD** [comment] 2023-09-27 15:47
@attila-fazekas Look for the heading **"If you have a buildSrc module"** [here on the setup page](https://splitties.github.io/refreshVersions/setup/#if-you-have-a-buildsrc-module). Notice it's slightly different from the root project.

**Comment by attila-fazekas** [comment] 2023-09-27 18:07
Hi @LouisCAD,
Thanks for investigating it. 
I did look at the provided link a couple of weeks ago and applied the suggested setup, but it did not make any difference.
Have just bumped the refreshVersions version to latest, you can see the resulted `versions.properties` [here](https://github.com/attila-fazekas/kolibrium/pull/55/files)

**Comment by LouisCAD** [comment] 2023-09-28 11:09
@attila-fazekas I see you have defined no repositories in the buildSrc. Can you try adding `mavenCentral()` as done [here](https://github.com/LouisCAD/Splitties/blob/e857f44aa9c1af2d7a8ea83eea79af6c7ad534c9/buildSrc/build.gradle.kts#L9-L12)?

**Comment by attila-fazekas** [comment] 2023-09-28 17:04
@LouisCAD that solved the issue 🎉 
Thanks a lot!
